version: "2"
services:
  php7:
    build:
      context: ./
      dockerfile: ./docker/php7/Dockerfile
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_IDE_CONFIG: serverName=phpnw.dev
    volumes:
      - ./:/var/www/sites/phpnw.dev/:consistent
      - ./vendor/:/var/www/sites/phpnw.dev/vendor/:ro
      - ./docker/php7/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
  mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_DATABASE: phpnw-dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Europe/London
    volumes:
      - ./docker/mysql/initial_sql/:/docker-entrypoint-initdb.d/:ro
      - ./docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf:ro
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./:/var/www/sites/phpnw.dev/:delegated
      - ./vendor/:/var/www/sites/phpnw.dev/vendor/:ro
      - ./docker/apache/conf.d/php.conf:/etc/httpd/conf.d/php.conf:ro
      - ./docker/apache/conf.d/server.conf:/etc/httpd/conf.d/server.conf:ro
      - ./docker/apache/includes/:/etc/httpd/includes/:ro
      - ./docker/apache/letsencrypt/:/etc/letsencrypt/:ro
      - ./docker/apache/sites.d/:/etc/httpd/sites.d/:ro
      - ./docker/apache/ssl/:/etc/pki/tls/certs/phpnw.dev/:ro
  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
    restart: always
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - '63790:6379'
    restart: always
    volumes:
      - ./docker/redis/:/data:delegated
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
